# Generated by Django 3.2.3 on 2021-05-21 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bugreport',
            name='user',
        ),
        migrations.AddField(
            model_name='bugreport',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
